// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `basePath: /api/
securityDefinitions:
  bearerAuth:
    name: Authorization
    in: header
    type: apiKey
definitions:
  model.RestResponse:
    properties:
      code:
        type: integer
      data: {}
      errorDetails: {}
      message:
        type: string
    type: object
info:
  contact:
    email: asif.hajiyev@outlook.com
  description: This is a Driver Location API to save them and search
  title: Driver Location API
  version: "1.0"
paths:
  /auth/get-token:
    get:
      description: Generating Bearer token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RestResponse'
      summary: Get Token to call match/* endpoints
      tags:
      - Auth
  /match:
    get:
      consumes:
      - application/json
      description: Matches given rider with the nearest driver by calculating distance
      parameters:
      - description: longitude of rider
        in: query
        name: longitude
        required: true
        type: string
      - description: latitude of rider
        in: query
        name: latitude
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RestResponse'
      summary: Match Rider with the nearest driver
      tags:
      - Match
      security:
      - bearerAuth: []
swagger: "2.0"
`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Driver Location API",
	Description:      "This is a Driver Location API to save them and search",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
